app = "your-bot-name"  # CHANGE THIS to a unique name
primary_region = "syd"  # or "lax", "dfw" etc.

[build]
  dockerfile = "Dockerfile"

[env]
  DISCORD_TOKEN = "your_token_here"  # Or use fly secrets set

[http_service]
  internal_port = 8080  # For health checks
  force_https = true
